<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<h1 class="h3"><i class="bi bi-stars text-teal"></i> AI Symptom Checker</h1>
<p class="text-muted">Describe what you're noticing and we'll tell you how urgently your pet should be seen.</p>

<?php if (! $aiEnabled): ?>
    <div class="alert alert-secondary small">AI is not configured on this server; results come from the built-in keyword screening.</div>
<?php endif ?>

<div class="row g-3">
    <div class="col-lg-6">
        <div class="card shadow-sm">
            <div class="card-body">
                <form action="<?= site_url('ai/symptom-checker') ?>" method="post">
                    <?= csrf_field() ?>
                    <div class="mb-3">
                        <label class="form-label" for="pet_id">Pet (optional)</label>
                        <select class="form-select" id="pet_id" name="pet_id">
                            <option value="">— Not specified —</option>
                            <?php foreach ($pets as $p): ?>
                                <option value="<?= $p['id'] ?>" <?= (string) old('pet_id', $pet['id'] ?? '') === (string) $p['id'] ? 'selected' : '' ?>>
                                    <?= esc($p['name']) ?> (<?= esc($p['species']) ?>)<?= has_role('owner') ? '' : ' — ' . esc($p['owner_name']) ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="symptoms">Symptoms</label>
                        <textarea class="form-control" id="symptoms" name="symptoms" rows="6" maxlength="2000" required
                                  placeholder="e.g. My dog has vomited 3 times since this morning and won't eat."><?= esc(old('symptoms', service('request')->getPost('symptoms') ?? '')) ?></textarea>
                    </div>
                    <button class="btn btn-teal"><i class="bi bi-search-heart"></i> Check symptoms</button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <?php if ($result): ?>
            <div class="card ai-box shadow-sm">
                <div class="card-body">
                    <h2 class="h5">Urgency: <?= status_badge($result['level']) ?></h2>
                    <?php if ($result['level'] === 'emergency'): ?>
                        <div class="alert alert-danger fw-semibold"><i class="bi bi-exclamation-octagon"></i> Seek veterinary care immediately.</div>
                    <?php endif ?>
                    <p><?= esc($result['advice']) ?></p>
                    <p class="small text-muted mb-2"><?= esc($result['summary']) ?></p>
                    <?php if ($result['red_flags']): ?>
                        <p class="small mb-2"><strong>Warning signs noted:</strong> <?= esc(implode(', ', $result['red_flags'])) ?></p>
                    <?php endif ?>
                    <a class="btn btn-sm btn-teal" href="<?= site_url('appointments/new' . (! empty($pet['id']) ? '?pet_id=' . $pet['id'] : '')) ?>">Book an appointment</a>
                    <p class="small text-muted fst-italic mt-3 mb-0">
                        <?= $result['source'] === 'ai' ? 'Generated by AI.' : 'Generated by keyword screening.' ?>
                        This is not a diagnosis — always follow your veterinarian's advice.
                    </p>
                </div>
            </div>
        <?php else: ?>
            <div class="card shadow-sm h-100"><div class="card-body text-muted d-flex align-items-center justify-content-center">
                The assessment will appear here.
            </div></div>
        <?php endif ?>
    </div>
</div>
<?= $this->endSection() ?>
